name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Red Hacker Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AreyMadhav
          outputs: |
            dist/snake-red.svg
            dist/snake-red-dark.svg
          color_snake: "#ff0033"
          color_dots: |
            #161b22
            #5a0000
            #990000
            #ff0033
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
